---
- name: create saybot group
  group: name=saybot 
  sudo: true

- name: create user saybot
  user: name=saybot
  sudo: true
  tags: users

- user: name={{ item.name }} groups=saybot append=yes
  with_items: users
  sudo: true
  tags: users

- name: set up authorized_keys for saybot
  authorized_key: user=saybot key="{{ lookup('file', item.1) }}"
  with_subelements:
    - users
    - authorized_keys
  sudo: true
  tags: users
