---
- name: create users
  user: name={{ item.name }} append=yes
  with_items: "{{users}}"
  become: true
  become_method: sudo
  tags: users

- name: set up authorized_keys
  authorized_key: user={{ item.0.name }} key="{{ lookup('file', item.1) }}"
  with_subelements:
    - "{{users}}"
    - authorized_keys
  become: true
  become_method: sudo
  tags: users
